ui=fluidPage(
  setBackgroundColor(color='white'),
  tags$style( 
    '.nav-tabs { border-color: #31408C;tabs-color:#31408C}',
    '.nav-tabs-custom .nav-tabs li.active {
             border-top-color: #4176A3;}'
  ),
  h1(img(src='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSXrLroJ5kCwXq5MADOkTatSakCYUAF42fSFw&usqp=CAU',
         width=450,height=150)), 
  h5(strong(em('¿Las condiciones iniciales de las comunas son relevantes para explicar los contagios?'),style='color:#31408C')), #CABECERA
  tabsetPanel(tabPanel('Introducción',
                       column(1),
                       column(9,
                              br(),
                              h4(strong('¿Qué nos proponemos con este proyecto?'),style='color:#31408C'),
                              p('En el marco del desafío final del programa de', em(strong('Data Analytics de la ',a(href='https://eant.tech/home','EANT'))), ', nos proponemos establecer condiciones iniciales para cada comuna en el marco de la pandemia de COVID-19 y analizar qué relación guardan las mismas con los casos positivos.'),
                              p('Para esto, analizaremos distintas variables relevantes en la contención de la actual crisis sanitaria:'),
                              tags$div(tags$ul(
                                tags$li('Sistema de salud público y privado'),
                                tags$li('Condiciones de vivienda y hacinamiento'),
                                tags$li('Calidad del trabajo, teletrabajo y empleo no registrado'),
                                tags$li('Disponibilidad de comercios de cercanía') 
                              ),
                              p('Todas estas variables serán analizadas por comuna y contrastadas con la cantidad de contagios registrados.'),
                              p('Al finalizar este análisis, se intentará responder si un mejor o peor desempeño en estos factores se correlaciona con la cantidad de contagios, y qué comunas son más vulnerables.'))),
                       column(1)), #HASTA ACÁ INTRODUCCIÓN 
              tabPanel('Estado de situación',
                       navlistPanel(
                         tabPanel('Distribución de los casos',
                                  br(),
                                  fluidRow(
                                    column(3,
                                           selectInput(inputId = 'barrio',
                                                       label = 'Consulte qué barrios hay en cada comuna:',
                                                       choices = sort(unique(df_COVID$COMUNA)),
                                                       selected = 'COMUNA 01'),
                                           tableOutput(outputId = 'tablacomu')
                                    ),
                                    column(8,
                                           plotlyOutput(outputId = 'casos1'))),
                                  br(),
                                  p(em('*Datos extraídos del Boletín Epidemiológico Semanal de la CABA al 31/07/20'))
                         ),
                         tabPanel('Casos cada 100.000 habitantes',
                                  br(),
                                  plotlyOutput(outputId = 'casos100'),
                                  br(),
                                  p(em('*Datos extraídos del Boletín Epidemiológico Semanal de la CABA al 31/07/20'))),
                         tabPanel('Evolución de los casos, altas y fallecimientos diarios',
                                  br(),
                                  plotlyOutput(outputId = 'casos2'),
                                  br(),
                                  p(em('*Datos extraídos de los datos abiertos del GCBA al 31/07/20'))),
                         tabPanel('Evolución de los casos diarios por comuna',
                                  br(),
                                  plotlyOutput(outputId = 'casos2.1'),
                                  br(),
                                  p(strong(em('NOTA: Haga doble click sobre alguna de las comunas para ver la evolución de los casos individualmente'))),
                                  br(),
                                  p(em('*Datos extraídos de los datos abiertos del GCBA al 31/07/20'))),
                         tabPanel('Evolución de los casos por barrio',
                                  br(),
                                  selectInput(inputId = 'comuna',
                                              label = 'Seleccione la/s comuna/s que desea ver:',
                                              choices = sort(unique(df_COVID$COMUNA)),
                                              selected = 'COMUNA 01',
                                              multiple = TRUE),
                                  plotlyOutput(outputId = 'casos3'),
                                  br(),
                                  p(strong(em('NOTA: Recomendamos no seleccionar más de cuatro o cinco comunas, para una mejor visualización de los resultados'))),
                                  br(),
                                  p(em('*Datos extraídos del Boletín Epidemiológico Semanal de la CABA al 31/07/20'))
                         ),
                         tabPanel('Tipos de contagios registrados',
                                  br(),
                                  selectInput(inputId = 'comuna0',
                                              label = 'Elija la comuna a visualizar:',
                                              choices = sort(unique(df_COVID$COMUNA))),
                                  br(),
                                  plotOutput(outputId = 'tipoconta'),
                                  br(),
                                  p(em('*Datos extraídos de los datos abiertos del GCBA al 31/07/20'))),
                         tabPanel('Fallecimientos por rango etareo',
                                  br(),
                                  selectInput(inputId = 'comufalle',
                                              label = 'Seleccione la comuna que desea ver:',
                                              choices = sort(unique(df_COVID$COMUNA)),
                                              selected = 'COMUNA 01'),
                                  plotlyOutput(outputId = 'comunafalle'),
                                  br(),
                                  p(em('*Datos extraídos de los datos abiertos del GCBA al 31/07/20'))
                         ),
                         tabPanel('Metodología',
                                  br(),
                                  p('Para analizar el estado de situación se utilizaron datos extraidos de los ',a(href='https://www.buenosaires.gob.ar/coronavirus/datos/situacion-epidemiologica','datos abiertos del GCBA'),' y del ',a(href='https://www.buenosaires.gob.ar/salud/boletines-periodicos/boletines-epidemiologicos-semanales-2018-2019','Boletín epidemiológico de la Ciudad de Buenos Aires')), #LINK A LA PAGINA DONDE ESTAN LOS INFORMES
                                  p('Las semanas epidemiológicas relevadas son:'),
                                  tags$div(tags$ul(
                                    tags$li('SEMANA 14: 17 de abril'),
                                    tags$li('SEMANA 15: 24 de abril'),
                                    tags$li('SEMANA 16: 1 de mayo'),
                                    tags$li('SEMANA 17: 8 de mayo'),
                                    tags$li('SEMANA 18: 15 de mayo'),
                                    tags$li('SEMANA 19: 22 de mayo'),
                                    tags$li('SEMANA 20: 29 de mayo'),
                                    tags$li('SEMANA 21: 5 de junio'),
                                    tags$li('SEMANA 22: 12 de junio'),
                                    tags$li('SEMANA 23: 19 de junio'),
                                    tags$li('SEMANA 24: 26 de junio'),
                                    tags$li('SEMANA 25: 3 de julio'),
                                    tags$li('SEMANA 26: 10 de julio'),
                                    tags$li('SEMANA 27: 17 de julio'),
                                    tags$li('SEMANA 28: 24 de julio'),
                                    tags$li('SEMANA 29: 31 de julio')))))), 
              tabPanel('Mapas',
                       fluidRow(column(3,
                                       br(),
                                       selectInput(inputId = 'rank',
                                                   label = 'Seleccione la variable a evaluar',
                                                   choices = names(puntajes)[15:19]),
                                       br(),
                                       h4('Descripción de la variable:',style='color:#31408C'),
                                       br(),
                                       textOutput(outputId = 'texto'),
                                       br(),
                                       h4('Las seis comunas con peores resultados son:',style='color:#31408C'),
                                       br(),
                                       fluidRow(column(2),
                                                column(8,
                                                       tableOutput(outputId = 'tabla_rank')),
                                                column(2))),
                                column(8,
                                       br(),
                                       br(),
                                       br(),
                                       br(),
                                       leafletOutput(outputId = 'mapas', width = "100%", height = 400)))),
              
              tabPanel('Tabla de puntajes',
                       br(),
                       dataTableOutput(outputId = 'puntajes')),
              
              
              tabPanel('Conclusiones',
                       br(),
                       fluidRow(column(1),
                                column(10,
                                       h4('En base a lo analizado, concluimos:'),
                                       p('El conjunto de variables elegidas es relevante para explicar la dinámica de los contagios por COVID-19 en las diferentes comunas de la Ciudad.'),
                                       p('En particular, encontramos que al sur de la ciudad, donde las comunas registraron los peores puntajes, se da la mayor tasa de casos positivos cada 100.000 habitantes.'),
                                       p('También se ve que las condiciones iniciales del oeste de la ciudad no son muy distintas a las del sur, aunque sí se observa una diferencia significativa en los casos cada 100.000 habitantes. Esto puede guardar relación con que la mayoría de las comunas con mas casos (1,4,7 y 9) tienen en su territorio barrios populares, en los que el GCBA realizó rastreos de casos temprano a través del Plan Detectar.'),
                                       p('Adicionalmente, podemos decir que nuestros indicadores de Salud, Vivienda y Empleo son los más relevantes para explicar la situación epidemiológica de cada comuna.')),
                                column(1)),
                       hr(),
                       br(),
                       fluidRow(column(6,
                                       leafletOutput(outputId = 'mapacon1',width = "100%", height = 400),
                                       br(),
                                       tableOutput(outputId = 'tablacon1')),
                                column(6,
                                       leafletOutput(outputId = 'mapacon2',width = "100%", height = 400),
                                       br(),
                                       tableOutput(outputId = 'tablacon2')))),
              
              
              tabPanel('Nosotros',
                       column(1),
                       column(10,
                              br(),
                              h3(strong('El equipo'),style='color:#31408C'),
                              br(),
                              h5('Alan Politis - Licenciado en Economía (UNLaM) - ',
                                 a(href='https://www.linkedin.com/in/alanpolitis/','LinkedIn'),
                                 ' - ',
                                 a(href='https://www.github.com/alanpolitis','GitHub')),
                              h5('Ignacio Ruiz - Licenciado en Economía (UBA) - ',
                                 a(href='https://www.linkedin.com/in/ignacio-ruiz-17314968','LinkedIn'),
                                 ' - ',
                                 a(href='https://www.github.com/ruizignacioo','GitHub')),
                              h5('Valeria Fernández - Licenciada en Economía (UNLaM) - ',
                                 a(href='https://www.linkedin.com/in/valeria-sofía-fernández/','LinkedIn'),
                                 ' - ',
                                 a(href='https://www.github.com/valesfer','GitHub')),
                              hr(),
                              br(),
                              h3(strong('Los profesores'),style='color:#31408C'),
                              br(),
                              h5('Romina Méndez'),
                              h5('Julio Spairani'),
                              br(),
                              hr(),
                              br(),
                              h3(strong('La escuela'),style='color:#31408C'),
                              br(),
                              h4('EANT - Escuela Argentina de Nuevas Tecnologías'),
                              h5('Escuela de ',a(href='https://eant.tech/escuela-de-ciencias-de-datos','Ciencia de Datos')),
                              br(),
                              hr(),
                              br(),
                              h3(strong('El proyecto'),style='color:#31408C'),
                              br(),
                              h5('Este proyecto fue llevado a cabo en el marco del desafío final del ',
                                 a(href='https://eant.tech/escuela-de-ciencias-de-datos/programas/data-analytics','Programa de Data Analytics'),
                                 'realizado entre el 05 de Mayo y el 21 de julio del 2020.'),
                              h5('En medio de la pandemia mundial del COVID-19, nos pareció interesante abordar este tema para descubrir qué factores fueron determinantes de la cantidad de contagios en la Ciudad de Buenos Aires.'),
                              h5('Para esto, utilizamos diversas bases de datos, obtenidas de:'),
                              h5(tags$div(tags$ul(
                                tags$li(a(href='https://data.buenosaires.gob.ar/dataset','Datos Abiertos de la Ciudad de Buenos Aires')),
                                br(),
                                tags$li(a (href=                                               'https://www.buenosaires.gob.ar/salud/boletines-periodicos/boletines-epidemiologicos-semanales-2018-2019',
                                           'Boletín Epidemiológico de la Ciudad de Buenos Aires')),
                                br(),
                                tags$li(a     (href='https://www.indec.gob.ar/indec/web/Institucional-Indec-BasesDeDatos-1',
                                               'Encuesta Permanente de Hogares (Nacional - INDEC)')),
                                br(),
                                tags$li(a(href=' https://www.estadisticaciudad.gob.ar/eyc/?page_id=702','Encuesta Anual de Hogares (CABA)'))
                              ))),
                              h5('Desarrollamos el análisis utilizando Rstudio, con los siguientes paquetes:'),
                              h5(tags$div(tags$ul(
                                tags$li('tidyverse'),
                                br(),
                                tags$li('shiny'),
                                br(),
                                tags$li('htmltools'),
                                br(),
                                tags$li('ggplot2'),
                                br(),
                                tags$li('plotly'),
                                br(),
                                tags$li('leaflet')
                              ))),
                              br(),
                              br()
                              
                              
                       ),
                       column(1))))
